### ISSUE TITLE
different min. requirements

### ISSUE THREAD

**Issue by timse201** [pluginkollektiv/publish-confirm#15]
https://github.com/pluginkollektiv/publish-confirm/blob/master/readme.txt#L5

https://github.com/pluginkollektiv/publish-confirm/blob/master/readme.txt#L39

https://github.com/pluginkollektiv/publish-confirm/blame/master/README.md#L30

**Comment by bueltge** [comment]
We should only support the least two versions, more is really to hard for testing.
