### ISSUE TITLE
Extend to submit, update, schedule and delete

### ISSUE THREAD

**Issue by bueltge** [pluginkollektiv/publish-confirm#18]
It would like to suggest having the confirmation dialog appear as well when trying to submit, update, schedule or delete a WordPress post/page.

Or could this be done via a filter?
Maybe an idea to solve different requirement. Currently we exclude only the 'Schedule' status via https://github.com/pluginkollektiv/publish-confirm/blob/5323a652e65a3489fa2f0050572a89cf73ccbaeb/inc/publish-confirm.php#L143

**Comment by Zodiac1978** [comment]
Related: https://wordpress.org/support/topic/misleading-message-when-post-is-scheduled/#post-5269485

**Comment by bueltge** [comment]
In the context of 
>As the Gutenberg editor introduced in WordPress 5.0 contains a similar functionality, the development of this plugin is discontinued. The plugin only supports the classic editor (works fine even when using WordPress 5.0 with the Classic Editor plugin).

we leave the current status und close this issue.
