### ISSUE TITLE
Publish confirm simply stopped working

### ISSUE THREAD

**Issue by JaneaMastandrea** [pluginkollektiv/publish-confirm#19]
Hi,

I am not a programmer. I have a WordPress fashion blog. I was using the Publish confirm plugin and LOVED it. It saved me from sending out an unfinished post to my subscribers more than once. Suddenly - within the last week - it stopped asking me if I was sure I wanted to publish. I deactivated it and reinstalled it. But this doesn't seem to have worked.

Can you please offer me some guidance to getting the plugin working again? I didn't change anything on my blog other than maybe updating to the newest WordPress version - I don't remember when that was.

Thanks!
Janea

**Comment by bueltge** [comment]
Have you changed other plugins, themes? Please, if you are inside the edit post screen; open the console - F12 inside the browser (use Chrome, if you have) and look for  a red and yellow icon on the right top side. Click on the red icon and ass the screenshot here, if you have a red or yellow icon. Like my exmaple
![console](https://cloud.githubusercontent.com/assets/133425/24544138/7c90bdb6-1602-11e7-8e34-746348ff0490.png)

**Comment by Zodiac1978** [comment]
Closing this  because of missing feedback.
