### ISSUE TITLE
Add options page

### ISSUE THREAD

**Issue by Zodiac1978** [pluginkollektiv/publish-confirm#20]
At the moment we just allow changing the text via filter. We could add an option page for it, like suggested here (ignore the rude tonality there):
https://wordpress.org/support/topic/ziemlich-unhandelbar-sehr-mau/

Additionally we could allow to toggle the custom post type and maybe the status (private, scheduled, etc.) for which the confirmation should be added.

**Comment by bueltge** [comment]
So much effort, maintenance for this topic; maybe a how to add on plugin should also help.  We have 1000 active installations, not more. And how much users will change this via options page?

**Comment by bueltge** [comment]
In the context of 
>As the Gutenberg editor introduced in WordPress 5.0 contains a similar functionality, the development of this plugin is discontinued. The plugin only supports the classic editor (works fine even when using WordPress 5.0 with the Classic Editor plugin).

we should leave the current status und close this issue, ok @Zodiac1978 ?
