### ISSUE TITLE
Implement text domain best practices

### ISSUE THREAD

**Issue by neverything** [pluginkollektiv/publish-confirm#9]
In `inc/publish_confirm.class.php` there are few non-best-practices for the text-domain with the current implementation:

* [ ] Missing text domain: https://github.com/pluginkollektiv/publish-confirm/blob/master/inc/publish_confirm.class.php#L93
* [ ] Variable in a translation function is a no go: https://github.com/pluginkollektiv/publish-confirm/blob/master/inc/publish_confirm.class.php#L54-L70

**Comment by bueltge** [comment]
@neverything The hint for line 93 is wrong. It is right here, that it not use a text domain. The source use the wp default from core, without textdomain to check, is it the string form the core language file. 

The other point are valid in my mind. But I think the check was for faster run, WP will always load a translation file, also it is not inside the language directory of a plugin. But I think also this a topic for the core, inside the plugin not helpful.

**Comment by Zodiac1978** [comment]
We shouldn't rely on core strings. It is recommended that every string in a plugin is translated by the plugin itself.

**Comment by bueltge** [comment]
@Zodiac1978 you have right. But the current implementation of this plugin use the core string for the comparison for the popup. If we add the plugin translation and is not equal to the core, then don't work the plugin. 
I think, we should change the plugin to check without a translatable string, is not really god. 

Also I think it is a good idea to use this for change to the idea of @swissspidy in issue #8 . But this should decided by the team of pluginkollektiv, it is a change for users of the plugin. This was the point, that I not implemented this in my changes.

**Comment by Zodiac1978** [comment]
@bueltge You are right. I should have read the code a little bit more. In this situation we should really use the core string.

Or we switch to the solution described in #8 - I would vote for that.

**Comment by bueltge** [comment]
The follow checkboxes simulate a voring for switch to ne UI, more WP typical UI from #8 ;)

[] @Zodiac1978 
[] @glueckpress 
[] @Drivingralle 
[] @staude 
[] @StephanieWiermann

**Comment by swissspidy** [comment]
>  But the current implementation of this plugin use the core string for the comparison for the popup. If we add the plugin translation and is not equal to the core, then don't work the plugin. 

Correct. But I'm sure there are ways to implement that alert box without relying on that core string.

**Comment by bueltge** [comment]
I think also to. The check with the string is not really fine. Maybe I find again a night for writing code. Thanks for hint the blind. ;)

**Comment by bueltge** [comment]
@Zodiac1978 I have change the original js source, that we not check on the language string. Now we check for the "name" attribute and so is it not necessary to check on a translatable string.

But I haven't change the UI topic, not enough feedback of the voting above.
